### ISSUE TITLE
Is there a way to fix missing base report?

### ISSUE THREAD

**Issue by alexweininger** [codecov/codecov-node#121]
It seems like there is no way to retroactively set the base report. How does one fix this issue? I would rather not make a new repository and start from scratch.

**Comment by chuck-imperato** [comment]
We are having the same issue and we are about to abandon codecov.  We've had nothing but problems with it because it doesn't update the status checks in Github.  Incredibly frustrating.

**Comment by Luttik** [comment]
@chuck-imperato what alternative are you (planning on) using.

**Comment by thomasrockhu** [comment]
I'm going to close this out due to age, but if you are still experiencing issues, please open a ticket in our [community boards](https://community.codecov.io)

@alexweininger, you will need to upload a coverage report for the base commit. Because Codecov has no coverage report, we have nothing to compare against.
