### ISSUE TITLE
Repo token was required for open source repo in circle ci

### ISSUE THREAD

**Issue by kt3k** [codecov/codecov-node#16]
It's not a critical issue because a workaround is available, but I think this isn't a supposed behaviour.

I built my open source repo `kt3k/ScenarioScript` in circle ci and tried to send coverage data using `codecov` module.
But it failed and showed this error:

```
==> Uploading reports
    HTTP 400
Please provide the repository token to upload reports via `-t :repository-token`
```

https://circleci.com/gh/kt3k/ScenarioScript/2
https://circleci.com/gh/kt3k/ScenarioScript/3
https://circleci.com/gh/kt3k/ScenarioScript/4

(I retried 2 times, but those didn't make difference.)

When I supplied `CODECOV_TOKEN` env variable, it succeeded.

https://circleci.com/gh/kt3k/ScenarioScript/6

I think this is supposed to work without repo token.

**Comment by stevepeak** [comment]
@kt3k it is supposed to work without a token. I think the issue was that the repository was not yet in the Codecov database. Do you recall accessing the project in Codecov before the build?

**Comment by kt3k** [comment]
Thanks for the quick response!

I didn't know I need to access the project before the build and that's the cause. Thanks! :smile:

**Comment by dkebler** [comment]
I keep getting this same error message after following all the docs and making sure I accessed the project.  Even with the error the data is making it to codecov and is visible in a badge so why the error?

So Is that error only because I am running codecov locally?  Was codecov package only intended to run and pass the data to codecov.io when doing a travis-cl build after the push the github and thus directly from travis ci?  If so that explains it.
