### ISSUE TITLE
partial line coverage removed?

### ISSUE THREAD

**Issue by jdalton** [codecov/codecov-node#18]
I've noticed for the last few weeks that codecov is [no longer showing me](https://codecov.io/gh/lodash/lodash) partial line coverage.
Has something changed?

My current coverage run looks like [this](https://github.com/lodash/lodash/blob/a43065ec08227c4d9c7f124213f8ef9fece147c1/.travis.yml#L64-L66).

**Comment by stevepeak** [comment]
@jdalton Thanks for pointing this out! We are enabling JS partial coverage in the next couple days in beta to receive customer feedback.

It was once enabled by default, but there were a growing number of projects that did not have accurate data due to the uploaded reports providing bad or inconsistent data.

I'll return here to express how to enter beta. Thanks!

**Comment by jdalton** [comment]
:metal:

**Comment by stevepeak** [comment]
@jdalton I've invited you to our Slack room to beta this feature 👍 if you are interested ping me (at)steve. Cheers!

**Comment by jdalton** [comment]
Thank you!
